name: Release Extension

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build and zip Chrome extension
        run: bun run zip
        
      - name: Build and zip Firefox extension
        run: bun run zip:firefox

      - name: Create Release
        uses: softprops/action-gh-release@v4
        with:
          files: |
            .output/*.zip
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
